services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5172:5172"
    volumes:
      - yazio-data:/data
    networks:
      - yazio-net

volumes:
  yazio-data:

networks:
  yazio-net:
    driver: bridge
