version: '3.8'

services:
  backend:
    build:
      context: https://github.com/greg35/YazioWeb.git#main:backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - yazio-data:/data
    networks:
      - yazio-net

  frontend:
    build:
      context: https://github.com/greg35/YazioWeb.git#main:frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - yazio-net

volumes:
  yazio-data:

networks:
  yazio-net:
    driver: bridge
